### ISSUE TITLE
Expose vsphere-categories Labels Configuration in vSphere CSI Helm Chart

### ISSUE THREAD

**Issue by pratikjagrut** [rancher/vsphere-charts#106]
### **Is your feature request related to a problem? Please describe.**

The Rancher vSphere CSI Helm chart does not expose the `vsphere-categories` labels configuration (`topology-categories`) directly through chart values. Users must manually edit the `configTemplate` in the chart's `values.yaml` file to add a `[Labels]` section for enabling CSI Topology, which is error-prone and increases configuration overhead.

### **Describe the solution you'd like**

Update the Rancher vSphere CSI Helm chart to expose the `vsphere-categories` labels configuration as configurable options in `values.yaml` and `questions.yaml`. This will allow users to enable and configure topology labels directly via Helm values or Rancher's UI without manual edits.

#### Proposed Changes:
1. **Update `values.yaml`:**
   Add a new `labels` section under the existing `vCenter` block:
   ```yaml
   vCenter:
     labels:
       enabled: false
       topologyCategories: "k8s-region, k8s-zone"
     configSecret:
       configTemplate: |
         [Global]
         cluster-id = {{ required ".Values.vCenter.clusterId must be provided" (default .Values.vCenter.clusterId .Values.global.cattle.clusterId) | quote }}
         user = {{ .Values.vCenter.username | quote }}
         password = {{ .Values.vCenter.password | quote }}
         port = {{ .Values.vCenter.port | quote }}
         insecure-flag = {{ .Values.vCenter.insecureFlag | quote }}

         [VirtualCenter {{ .Values.vCenter.host | quote }}]
         datacenters = {{ .Values.vCenter.datacenters | quote }}

         {{- if .Values.vCenter.labels.enabled }}
         [Labels]
         topology-categories = {{ .Values.vCenter.labels.topologyCategories | quote }}
         {{- end }}
   ```

2. **Update `questions.yaml`:**
   Add corresponding fields to expose these options in Rancher's UI:
   ```yaml
   questions:
   - variable: vCenter.labels.enabled
     default: false
     description: "Enable CSI topology labels configuration"
     type: boolean
     label: Enable Topology Labels

   - variable: vCenter.labels.topologyCategories
     default: "k8s-region, k8s-zone"
     description: "Specify topology categories for CSI (comma-separated list)"
     type: string
     label: Topology Categories
     show_if: "vCenter.labels.enabled=true"
   ```

### **Describe alternatives you've considered**

Manual configuration by editing the Helm chart's `values.yaml` file during installation. While functional, this approach is error-prone and not user-friendly.

### **Additional context**

SURE-9495
