### ISSUE TITLE
with windows server 2022 the sockets for csi are not correct

### ISSUE THREAD

**Issue by pgress** [rancher/vsphere-charts#43]
**vSphere Server Info**
- vSphere version:  7.0.3

**Rancher Server Setup**
- Rancher version: v2.7.1 
- Installation option (Docker install/Helm Chart): Helm Chart
    - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.10+rke2r1
- Cluster Type (Local/Downstream): Hosted vSphere
    - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
We installed the csi-driver via the rancher-gui and use windows server 2022 standard
in the `vsphere-csi-node-windows` pods the `node-driver-registrar` crashes due to an unreachable socket. 
The Pod logs print out the following:
```
I0307 10:51:09.178916    8264 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix \\\\var\\\\lib\\\\kubelet\\\\plugins\\\\csi.vsphere.vmware.com\\\\csi.sock: connect: A socket operation was attempted to an unreachable network.",}
```

A workaround is to edit the daemonset `vsphere-csi-node-windows` and replace \\ with \ in the environment of the container.
It would look like this afterwards:
```
        env:
        - name: ADDRESS
          value: unix://C:\csi\csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: \var\lib\kubelet\plugins\csi.vsphere.vmware.com\csi.sock
```
